'use client';

export {
  resolveAcademyId,
  LEGAL_CONSENT_REQUIRED_CODE,
  LEGAL_CONSENT_REQUIRED_EVENT,
  postJson,
} from './client/core';
export type { RequestOptions } from './client/core';
export {
  getPublicJson,
  postPublicJson,
  getJson,
  patchJson,
  login,
  apiErrorCode,
  register,
  logout,
  me,
  quickSignup,
  quickJoin,
  quickStartAcademy,
  createPanelHandoff,
  checkAcademySlug,
  getLegalDocuments,
} from './client/http-helpers';
export type {
  LoginPayload,
  RegisterPayload,
  QuickSignupPayload,
  QuickStartResult,
  LegalDocumentSummary,
  LegalPendingDocument,
  LegalChangeLine,
} from './client/http-helpers';
export {
  getLegalAcceptanceStatus,
  getLegalAcceptanceDiff,
  acceptPlatformLegalDocuments,
  listNotifications,
  getUnreadNotificationCount,
  markNotificationRead,
  markAllNotificationsRead,
  requestRefund,
  getMyLegalAcceptances,
  validatePhoneAndEmail,
  sendEmailOtp,
  sendPhoneOtp,
  loginByPhoneOtp,
  loginByEmailOtp,
  verifyEmailOtp,
  verifyPhoneOtp,
  forgetPassword,
  changePassword,
  updateProfile,
  uploadImage,
} from './client/legal-and-profile';
export type {
  LegalDocumentDiff,
  NotificationRow,
  SendOtpPayload,
  VerifyOtpPayload,
  ForgetPasswordPayload,
} from './client/legal-and-profile';
export {
  updateStore,
  getLesson,
  getLessonLiveSession,
  getCourseQnAs,
  createCourseQnA,
  approveCourseQnA,
  answerCourseQnA,
  getCourseReviews,
  createCourseReview,
  getActiveSessions,
  revokeSession,
  logoutAllDevices,
} from './client/lessons-and-quizzes';
export type {
  LessonLiveSession,
  CourseQnA,
  CourseQnAList,
  CourseReview,
  RatingCounts,
  CourseReviewsResponse,
  ActiveSession,
  QuizQuestionType,
  QuizAttemptStatus,
  QuizOption,
  QuizQuestion,
  QuizAttemptRow,
  StudentQuiz,
  QuizGate,
} from './client/lessons-and-quizzes';
export {
  getLessonQuiz,
  getSeasonQuiz,
  getCourseQuiz,
  getSessionQuiz,
  getQuizGates,
  startQuizAttempt,
  saveQuizAnswers,
  submitQuizAttempt,
  getQuizAttempt,
  getDiscussionThread,
  findDiscussionThread,
  postDiscussionMessage,
  uploadDiscussionAttachment,
  uploadDiscussionZip,
  subscribeDiscussionEvents,
} from './client/assessment';
export type {
  QuizAnswer,
  QuizAttempt,
  AnswerInput,
  DiscussionAttachment,
  DiscussionMessage,
  DiscussionParent,
  TicketStatus,
  TicketPriority,
  TicketCategory,
  TicketPerson,
  TicketResponsible,
  TicketListItem,
  TicketAttachmentView,
  TicketMessageView,
  TicketCapabilities,
  TicketDetail,
} from './client/assessment';
export {
  listTicketCourses,
  listSupportResponsibles,
  listMySupportTickets,
  getSupportTicket,
  createSupportTicket,
  replySupportTicket,
  requestSupportCall,
  closeSupportTicket,
  rateSupportTicket,
  uploadSupportAttachment,
  uploadAssignmentImage,
  holdSeats,
  releaseSeatHold,
} from './client/tickets-and-seats';
export type { CreateTicketPayload, TicketCourseOption, SeatHold } from './client/tickets-and-seats';
