/**
 * GENERATED by Backend/tools/build-log-catalog.mjs — run `pnpm log:catalog` after
 * adding a log call. Descriptions are hand-written and preserved across runs;
 * the event/action/field lists are derived from the code and must not be edited
 * by hand. This file is the single index of every log this app can emit.
 */
import type { LogCatalog } from './logger';

export const LOG_CATALOG = {
  Account: {
    description: 'The account area a student uses on the public website.',
    actions: {
      AvatarCropFailed: {
        description: 'Browser could not crop the picked avatar before upload.',
        level: 'error',
        fields: [] as const,
      },
      AvatarRemoved: {
        description: 'Account avatar removed.',
        level: 'info',
        fields: [] as const,
      },
      AvatarUpdated: {
        description: 'Account avatar updated.',
        level: 'info',
        fields: ['size_bytes'] as const,
      },
      AvatarUpdateFailed: {
        description: 'Account avatar update failed.',
        level: 'error',
        fields: ['size_bytes'] as const,
      },
    },
  },
  Auth: {
    description: 'Sign-in session upkeep on the public website: token refresh, logout.',
    actions: {
      AccessTokenExpired: {
        description: 'Auth access token expired.',
        level: 'info',
        fields: [] as const,
      },
      BackendLogoutFailed: {
        description: 'Auth backend logout failed.',
        level: 'warn',
        fields: [] as const,
      },
      JwtSecretMissing: {
        description: 'Auth jwt secret missing.',
        level: 'warn',
        fields: [] as const,
      },
      LogoutFailed: {
        description: 'Auth logout failed.',
        level: 'error',
        fields: [] as const,
      },
      TokenRefreshed: {
        description: 'Auth token refreshed.',
        level: 'info',
        fields: [] as const,
      },
      TokenRefreshFailed: {
        description: 'Auth token refresh failed.',
        level: 'error',
        fields: [] as const,
      },
      TokenRefreshRejected: {
        description: 'Auth token refresh rejected.',
        level: 'warn',
        fields: ['status_code'] as const,
      },
    },
  },
  Cart: {
    description: 'The student cart syncing between the browser and the server.',
    actions: {
      SyncAfterRemovalFailed: {
        description: 'Cart sync after removal failed.',
        level: 'warn',
        fields: [] as const,
      },
      SyncFailed: {
        description: 'Cart sync failed.',
        level: 'error',
        fields: [] as const,
      },
      SyncRejected: {
        description: 'Cart sync rejected.',
        level: 'warn',
        fields: ['status_code'] as const,
      },
    },
  },
  ClassRequest: {
    description: 'Logs emitted by the ClassRequest domain.',
    actions: {
      BusyTimesFailed: {
        description: 'Class request busy times failed.',
        level: 'warn',
        fields: [] as const,
      },
      SubmitFailed: {
        description: 'Class request submit failed.',
        level: 'warn',
        fields: [] as const,
      },
      Submitted: {
        description: 'Class request submitted.',
        level: 'info',
        fields: ['course_id'] as const,
      },
    },
  },
  Legal: {
    description: 'Legal document publishing and user consent acceptance.',
    actions: {
      ConsentAccepted: {
        description: 'Legal consent accepted.',
        level: 'info',
        fields: ['document_count'] as const,
      },
      ConsentAcceptFailed: {
        description: 'Legal consent accept failed.',
        level: 'error',
        fields: ['document_count'] as const,
      },
    },
  },
  Media: {
    description: 'Video and file storage, transcoding and secure playback.',
    actions: {
      PlaybackSessionFailed: {
        description: 'Media playback session failed.',
        level: 'error',
        fields: ['error_name', 'video_id'] as const,
      },
      PlayerError: {
        description: 'Media player error.',
        level: 'error',
        fields: ['error_details', 'error_type', 'video_id'] as const,
      },
    },
  },
  Motion: {
    description: 'Scroll animations on public pages.',
    actions: {
      ScrollTriggerLoadFailed: {
        description: 'Motion scroll trigger load failed.',
        level: 'warn',
        fields: [] as const,
      },
    },
  },
  Payments: {
    description: 'Student and academy payments: checkout, gateway callbacks, refunds.',
    actions: {
      CheckoutGatewayPrompted: {
        description: 'Payments checkout gateway prompted.',
        level: 'info',
        fields: ['amount', 'gateway_count', 'kind'] as const,
      },
      CheckoutStarted: {
        description: 'Payments checkout started.',
        level: 'info',
        fields: ['amount', 'gateway_redirect', 'kind'] as const,
      },
      CheckoutStartFailed: {
        description: 'Payments checkout start failed.',
        level: 'error',
        fields: ['amount', 'http_status', 'kind'] as const,
      },
      RefundRequested: {
        description: 'Payments refund requested.',
        level: 'info',
        fields: ['has_reason'] as const,
      },
      RefundRequestRejected: {
        description: 'Payments refund request rejected.',
        level: 'warn',
        fields: ['has_reason'] as const,
      },
      SeatHoldExpired: {
        description: 'The 10-minute seat hold ran out while the checkout dialog was open.',
        level: 'warn',
        fields: ['group_id'] as const,
      },
      SeatHoldFailed: {
        description: 'Holding seats at checkout open failed (class full or not on sale).',
        level: 'warn',
        fields: [] as const,
      },
    },
  },
  Quiz: {
    description: 'A student taking a lesson quiz in the browser.',
    actions: {
      DraftSaveFailed: {
        description: 'Autosave of a student\'s in-progress quiz answers failed; the student keeps typing and sees an inline warning.',
        level: 'warn',
        fields: ['attempt_id'] as const,
      },
    },
  },
  RequestStorm: {
    description: 'Client-side circuit breaker: one API route called far above human speed.',
    actions: {
      Tripped: {
        description: 'A single route exceeded the per-window hit limit in the student\'s browser; protected routes force a sign-out and storage wipe.',
        level: 'error',
        fields: ['count', 'is_protected', 'method', 'route', 'window_ms'] as const,
      },
    },
  },
  SiteBlocks: {
    description: 'Rendering an academy site\'s page sections.',
    actions: {
      NoBlocks: {
        description: 'Site blocks no blocks.',
        level: 'warn',
        fields: [] as const,
      },
      NoVisibleBlocks: {
        description: 'Site blocks no visible blocks.',
        level: 'warn',
        fields: [] as const,
      },
      RenderFailed: {
        description: 'Site blocks render failed.',
        level: 'error',
        fields: ['block_id', 'block_type'] as const,
      },
    },
  },
  SiteCache: {
    description: 'Logs emitted by the SiteCache domain.',
    actions: {
      Revalidated: {
        description: 'Site cache revalidated.',
        level: 'info',
        fields: ['academy_slug'] as const,
      },
    },
  },
  SitePreview: {
    description: 'Preview rendering of an academy site template.',
    actions: {
      PresetEmpty: {
        description: 'Site preview preset empty.',
        level: 'warn',
        fields: ['draft', 'has_preset', 'has_token', 'template_key'] as const,
      },
      PresetFetchFailed: {
        description: 'Site preview preset fetch failed.',
        level: 'error',
        fields: ['draft', 'error_message', 'has_token', 'template_key'] as const,
      },
    },
  },
  SiteTheme: {
    description: 'Loading an academy site\'s theme and template.',
    actions: {
      ThemeConfigFetchFailed: {
        description: 'Site theme config fetch failed.',
        level: 'warn',
        fields: [] as const,
      },
      UiTemplateFetchFailed: {
        description: 'Site theme UI template fetch failed.',
        level: 'warn',
        fields: ['academy_slug', 'error_message'] as const,
      },
    },
  },
  Tutoring: {
    description: 'Logs emitted by the Tutoring domain.',
    actions: {
      JoinClassFailed: {
        description: 'Moving a 1:1 student into an open class failed.',
        level: 'warn',
        fields: [] as const,
      },
      JoinedClassFromPrivate: {
        description: 'A paid 1:1 student moved into an open class from the classroom.',
        level: 'info',
        fields: ['credit_granted', 'group_id', 'seats'] as const,
      },
    },
  },
} as const satisfies LogCatalog;

export type AppLogCatalog = typeof LOG_CATALOG;
