/**
 * Rouzan default copy — the catalogue half: courses, learning paths, the live
 * class calendar and the support team. Split from `defaults.ts` only to keep
 * both files readable; `ROUZAN_DEFAULTS` merges them.
 */

export const ROUZAN_CATALOG_DEFAULTS = {
  courses: {
    eyebrow: '۶ دورهٔ منتشرشده',
    title: 'از اولین حلقه تا دیپلوی روی سرور',
    ctaText: 'همهٔ دوره‌ها',
    items: [
      {
        token: 'javascript',
        level: 'مقدماتی',
        tone: 'a' as const,
        title: 'جاوااسکریپت، از صفر تا تسلط',
        body: 'بدون پیش‌نیاز. ۹ فصل، ۴۱ تمرین با بازبینی، و یک پروژهٔ نهایی.',
        hours: '۳۸ ساعت',
        chapters: '۹ فصل',
        rating: '۴٫۹',
        price: '۱٬۹۸۰٬۰۰۰',
      },
      {
        token: 'react · next',
        level: 'متوسط',
        tone: 'b' as const,
        title: 'ری‌اکت و نکست: ساخت یک محصول واقعی',
        body: 'یک فروشگاه کامل می‌سازیم: مسیریابی، کش، فرم، پرداخت، سئو.',
        hours: '۵۲ ساعت',
        chapters: '۱۲ فصل',
        rating: '۴٫۸',
        price: '۳٬۴۵۰٬۰۰۰',
      },
      {
        token: 'node · postgres',
        level: 'متوسط',
        tone: 'c' as const,
        title: 'بک‌اند با نود و پستگرس',
        body: 'طراحی جدول، تراکنش، ایندکس، و یک ای‌پی‌آی که زیر بار نمی‌افتد.',
        hours: '۴۶ ساعت',
        chapters: '۱۱ فصل',
        rating: '۴٫۹',
        price: '۲٬۹۸۰٬۰۰۰',
      },
      {
        token: 'typescript',
        level: 'پیشرفته',
        tone: 'c' as const,
        title: 'تایپ‌اسکریپت جدی',
        body: 'جنریک، تایپ شرطی، و اینکه چرا تایپ باز بدهی فنی است.',
        hours: '۲۲ ساعت',
        chapters: '۶ فصل',
        rating: '۴٫۷',
        price: '۱٬۴۵۰٬۰۰۰',
      },
      {
        token: 'vitest · ci',
        level: 'پیشرفته',
        tone: 'b' as const,
        title: 'تست‌نویسی و خط لولهٔ انتشار',
        body: 'تستی که واقعاً باگ می‌گیرد، و اکشنی که جمعه‌شب خوابت را نمی‌برد.',
        hours: '۱۸ ساعت',
        chapters: '۵ فصل',
        rating: '۴٫۶',
        price: '۱٬۲۸۰٬۰۰۰',
      },
      {
        token: 'architecture',
        level: 'پیشرفته',
        tone: 'a' as const,
        title: 'معماری فرانت‌اند در تیم چندنفره',
        body: 'مرزبندی ماژول‌ها، دیزاین‌سیستم، و بازنویسی تدریجی یک کد قدیمی.',
        hours: '۲۶ ساعت',
        chapters: '۷ فصل',
        rating: '۵٫۰',
        price: '۲٬۲۰۰٬۰۰۰',
      },
    ],
  },

  categories: {
    eyebrow: 'ترتیب پیشنهادی من',
    title: 'سه مسیر، بستهٔ به کاری که می‌خواهی بگیری',
    subtitle: 'دوره‌ها را جدا هم می‌توانی بخری؛ مسیر یعنی ترتیب درست و ۱۵٪ تخفیف مجموعه.',
    ctaText: 'دیدن مسیر',
    items: [
      {
        title: 'فرانت‌اند کاربردی',
        meta: '۶۰ ساعت · ۴ ماه با ۵ ساعت در هفته',
        featured: false,
        steps: [
          { no: '۰۱', title: 'جاوااسکریپت از صفر', meta: '۳۸ ساعت' },
          { no: '۰۲', title: 'ری‌اکت و نکست', meta: '۵۲ ساعت' },
          { no: '۰۳', title: 'تایپ‌اسکریپت جدی', meta: '۲۲ ساعت' },
        ],
      },
      {
        title: 'فول‌استک از پایه',
        meta: '۱۳۴ ساعت · ۸ ماه · شامل بازبینی کد',
        featured: true,
        tag: 'پرطرفدارترین',
        steps: [
          { no: '۰۱', title: 'جاوااسکریپت از صفر', meta: '۳۸ ساعت' },
          { no: '۰۲', title: 'نود و پستگرس', meta: '۴۶ ساعت' },
          { no: '۰۳', title: 'ری‌اکت و نکست', meta: '۵۲ ساعت' },
          { no: '۰۴', title: 'پروژهٔ پایانی با دیپلوی', meta: '۴ هفته' },
        ],
      },
      {
        title: 'ارتقا برای شاغل‌ها',
        meta: '۴۴ ساعت · برای کسی که الان کد می‌زند',
        featured: false,
        steps: [
          { no: '۰۱', title: 'تایپ‌اسکریپت جدی', meta: '۲۲ ساعت' },
          { no: '۰۲', title: 'تست و خط لوله', meta: '۱۸ ساعت' },
          { no: '۰۳', title: 'معماری فرانت‌اند', meta: '۲۶ ساعت' },
        ],
      },
    ],
  },

  showcase: {
    eyebrow: 'تقویم مهر و آبان',
    title: 'جلسه‌های زندهٔ پرسش‌وپاسخ و کارگاه',
    subtitle: 'ضبط همهٔ جلسه‌ها تا ۴۸ ساعت بعد در پنل شما قرار می‌گیرد.',
    columns: ['جلسه', 'روز و ساعت', 'مخاطب', 'ظرفیت', 'وضعیت'],
    note: 'جلسه‌ها آنلاین برگزار می‌شود؛ لینک ورود ۳۰ دقیقه پیش از شروع پیامک می‌شود.',
    rows: [
      {
        title: 'پرسش‌وپاسخ هفتگی',
        note: 'هر هفته، آزاد برای همهٔ دانشجوها',
        when: 'سه‌شنبه · ۲۰:۰۰ تا ۲۱:۳۰',
        who: 'همهٔ دوره‌ها',
        seats: 'نامحدود',
        status: 'امشب',
        tone: 'live' as const,
        action: 'ورود به کلاس',
      },
      {
        title: 'کارگاه دیباگ عملی',
        note: 'روی کد خودتان، با اشتراک صفحه',
        when: 'پنجشنبه ۱۷ مهر · ۱۰:۰۰',
        who: 'متوسط و بالاتر',
        seats: '۴ از ۱۶ باقی',
        status: 'ظرفیت کم',
        tone: 'few' as const,
        action: 'ثبت‌نام',
      },
      {
        title: 'مصاحبهٔ فنی آزمایشی',
        note: '۴۵ دقیقه، با بازخورد کتبی',
        when: 'جمعه ۲۵ مهر · ۱۱:۰۰',
        who: 'فول‌استک، هفتهٔ ۲۰ به بعد',
        seats: '۱ از ۸ باقی',
        status: 'ظرفیت کم',
        tone: 'few' as const,
        action: 'ثبت‌نام',
      },
      {
        title: 'کارگاه پستگرس زیر بار',
        note: 'ایندکس، پلن کوئری، قفل‌ها',
        when: 'پنجشنبه ۸ آبان · ۱۰:۰۰',
        who: 'دورهٔ بک‌اند',
        seats: 'تکمیل',
        status: 'لیست انتظار',
        tone: 'full' as const,
        action: 'اطلاع‌رسانی به من',
      },
    ],
  },

  teachers: {
    eyebrow: 'تدریس با من است، بازبینی با ما',
    title: 'دستیارانی که تمرین‌های شما را می‌خوانند',
    ctaText: 'همکاری با ما',
    items: [
      {
        initials: 'م‌آ',
        name: 'مهدی آرین‌فر',
        role: 'مدرس دوره‌ها',
        bio: 'نُه سال مهندسی نرم‌افزار در دو تیم محصولی. همهٔ ویدیوها و بازبینی پروژهٔ پایانی با من است.',
        tone: 'base' as const,
      },
      {
        initials: 'ن‌س',
        name: 'نگار سلطانی',
        role: 'دستیار فرانت‌اند',
        bio: 'بازبینی تمرین‌های ری‌اکت و نکست. پاسخ در ساعات ۱۰ تا ۱۸.',
        tone: 'a' as const,
      },
      {
        initials: 'س‌ب',
        name: 'سعید براتی',
        role: 'دستیار بک‌اند',
        bio: 'پستگرس، داکر و دیپلوی. کارگاه دیباگ عملی را هم او اجرا می‌کند.',
        tone: 'b' as const,
      },
      {
        initials: 'ر‌ف',
        name: 'راضیه فتحی',
        role: 'پشتیبانی دانشجو',
        bio: 'ثبت‌نام، فاکتور و مشکل پنل. شنبه تا چهارشنبه، ۹ تا ۱۷.',
        tone: 'a' as const,
      },
    ],
  },
} as const;
